// suras.js

const suras = [
  { id: 1, nameArabic: "سورة الفاتحة", nameEnglish: "Al-Fatihah", nameBangla: "সূরা আল-ফাতিহা", totalAyahs: 7, revelationPlace: "Makkah" },
  { id: 2, nameArabic: "سورة البقرة", nameEnglish: "Al-Baqarah", nameBangla: "সূরা আল-বাক্বারাহ", totalAyahs: 286, revelationPlace: "Madinah" },
  { id: 3, nameArabic: "سورة آل عمران", nameEnglish: "Aal Imran", nameBangla: "সূরা আলে-ইমরান", totalAyahs: 200, revelationPlace: "Madinah" },
  { id: 4, nameArabic: "سورة النساء", nameEnglish: "An-Nisa", nameBangla: "সূরা আন-নিসা", totalAyahs: 176, revelationPlace: "Madinah" },
  { id: 5, nameArabic: "سورة المائدة", nameEnglish: "Al-Ma'idah", nameBangla: "সূরা আল-মায়েদাহ", totalAyahs: 120, revelationPlace: "Madinah" },
  { id: 6, nameArabic: "سورة الأنعام", nameEnglish: "Al-An'am", nameBangla: "সূরা আল-আন’আম", totalAyahs: 165, revelationPlace: "Makkah" },
  { id: 7, nameArabic: "سورة الأعراف", nameEnglish: "Al-A'raf", nameBangla: "সূরা আল-আ’রাফ", totalAyahs: 206, revelationPlace: "Makkah" },
  { id: 8, nameArabic: "سورة الأنفال", nameEnglish: "Al-Anfal", nameBangla: "সূরা আল-আনফাল", totalAyahs: 75, revelationPlace: "Madinah" },
  { id: 9, nameArabic: "سورة التوبة", nameEnglish: "At-Tawbah", nameBangla: "সূরা আত-তাওবাহ", totalAyahs: 129, revelationPlace: "Madinah" },
  { id: 10, nameArabic: "سورة يونس", nameEnglish: "Yunus", nameBangla: "সূরা ইউনুস", totalAyahs: 109, revelationPlace: "Makkah" },

  { id: 11, nameArabic: "سورة هود", nameEnglish: "Hud", nameBangla: "সূরা হুদ", totalAyahs: 123, revelationPlace: "Makkah" },
  { id: 12, nameArabic: "سورة يوسف", nameEnglish: "Yusuf", nameBangla: "সূরা ইউসুফ", totalAyahs: 111, revelationPlace: "Makkah" },
  { id: 13, nameArabic: "سورة الرعد", nameEnglish: "Ar-Ra'd", nameBangla: "সূরা আর-রা’দ", totalAyahs: 43, revelationPlace: "Madinah" },
  { id: 14, nameArabic: "سورة إبراهيم", nameEnglish: "Ibrahim", nameBangla: "সূরা ইবরাহীম", totalAyahs: 52, revelationPlace: "Makkah" },
  { id: 15, nameArabic: "سورة الحجر", nameEnglish: "Al-Hijr", nameBangla: "সূরা আল-হিজর", totalAyahs: 99, revelationPlace: "Makkah" },
  { id: 16, nameArabic: "سورة النحل", nameEnglish: "An-Nahl", nameBangla: "সূরা আন-নাহল", totalAyahs: 128, revelationPlace: "Makkah" },
  { id: 17, nameArabic: "سورة الإسراء", nameEnglish: "Al-Isra", nameBangla: "সূরা আল-ইসরাঃ", totalAyahs: 111, revelationPlace: "Makkah" },
  { id: 18, nameArabic: "سورة الكهف", nameEnglish: "Al-Kahf", nameBangla: "সূরা আল-কাহফ", totalAyahs: 110, revelationPlace: "Makkah" },
  { id: 19, nameArabic: "سورة مريم", nameEnglish: "Maryam", nameBangla: "সূরা মরিয়ম", totalAyahs: 98, revelationPlace: "Makkah" },
  { id: 20, nameArabic: "سورة طه", nameEnglish: "Ta-Ha", nameBangla: "সূরা ত্বা-হা", totalAyahs: 135, revelationPlace: "Makkah" },

  { id: 21, nameArabic: "سورة الأنبياء", nameEnglish: "Al-Anbiya", nameBangla: "সূরা আল-আম্বিয়া", totalAyahs: 112, revelationPlace: "Makkah" },
  { id: 22, nameArabic: "سورة الحج", nameEnglish: "Al-Hajj", nameBangla: "সূরা আল-হাজ্জ", totalAyahs: 78, revelationPlace: "Madinah" },
  { id: 23, nameArabic: "سورة المؤمنون", nameEnglish: "Al-Mu'minun", nameBangla: "সূরা আল-মু’মিনুন", totalAyahs: 118, revelationPlace: "Makkah" },
  { id: 24, nameArabic: "سورة النور", nameEnglish: "An-Nur", nameBangla: "সূরা আন-নূর", totalAyahs: 64, revelationPlace: "Madinah" },
  { id: 25, nameArabic: "سورة الفرقان", nameEnglish: "Al-Furqan", nameBangla: "সূরা আল-ফুরকান", totalAyahs: 77, revelationPlace: "Makkah" },
  { id: 26, nameArabic: "سورة الشعراء", nameEnglish: "Ash-Shu'ara", nameBangla: "সূরা আশ-শু’আরা", totalAyahs: 227, revelationPlace: "Makkah" },
  { id: 27, nameArabic: "سورة النمل", nameEnglish: "An-Naml", nameBangla: "সূরা আন-নামল", totalAyahs: 93, revelationPlace: "Makkah" },
  { id: 28, nameArabic: "سورة القصص", nameEnglish: "Al-Qasas", nameBangla: "সূরা আল-কাসাস", totalAyahs: 88, revelationPlace: "Makkah" },
  { id: 29, nameArabic: "سورة العنكبوت", nameEnglish: "Al-Ankabut", nameBangla: "সূরা আল-আনকাবূত", totalAyahs: 69, revelationPlace: "Makkah" },
  { id: 30, nameArabic: "سورة الروم", nameEnglish: "Ar-Rum", nameBangla: "সূরা আর-রূম", totalAyahs: 60, revelationPlace: "Makkah" },

  { id: 31, nameArabic: "سورة لقمان", nameEnglish: "Luqman", nameBangla: "সূরা লুকমান", totalAyahs: 34, revelationPlace: "Makkah" },
  { id: 32, nameArabic: "سورة السجدة", nameEnglish: "As-Sajda", nameBangla: "সূরা আস-সাজদাহ", totalAyahs: 30, revelationPlace: "Makkah" },
  { id: 33, nameArabic: "سورة الأحزاب", nameEnglish: "Al-Ahzab", nameBangla: "সূরা আল-আহযাব", totalAyahs: 73, revelationPlace: "Madinah" },
  { id: 34, nameArabic: "سورة سبإ", nameEnglish: "Saba", nameBangla: "সূরা সাবা", totalAyahs: 54, revelationPlace: "Makkah" },
  { id: 35, nameArabic: "سورة فاطر", nameEnglish: "Fatir", nameBangla: "সূরা ফাতির", totalAyahs: 45, revelationPlace: "Makkah" },
  { id: 36, nameArabic: "سورة يس", nameEnglish: "Ya-Sin", nameBangla: "সূরা ইয়াসীন", totalAyahs: 83, revelationPlace: "Makkah" },
  { id: 37, nameArabic: "سورة الصافات", nameEnglish: "As-Saffat", nameBangla: "সূরা আস-সাফ্ফাত", totalAyahs: 182, revelationPlace: "Makkah" },
  { id: 38, nameArabic: "سورة ص", nameEnglish: "Sad", nameBangla: "সূরা সাদ", totalAyahs: 88, revelationPlace: "Makkah" },
  { id: 39, nameArabic: "سورة الزمر", nameEnglish: "Az-Zumar", nameBangla: "সূরা আজ-জুমার", totalAyahs: 75, revelationPlace: "Makkah" },
  { id: 40, nameArabic: "سورة غافر", nameEnglish: "Ghafir", nameBangla: "সূরা গাফির", totalAyahs: 85, revelationPlace: "Makkah" },

  { id: 41, nameArabic: "سورة فصلت", nameEnglish: "Fussilat", nameBangla: "সূরা ফুসসিলাত", totalAyahs: 54, revelationPlace: "Makkah" },
  { id: 42, nameArabic: "سورة الشورى", nameEnglish: "Ash-Shura", nameBangla: "সূরা আশ-শূরা", totalAyahs: 53, revelationPlace: "Makkah" },
  { id: 43, nameArabic: "سورة الزخرف", nameEnglish: "Az-Zukhruf", nameBangla: "সূরা আজ-যুখরুফ", totalAyahs: 89, revelationPlace: "Makkah" },
  { id: 44, nameArabic: "سورة الدخان", nameEnglish: "Ad-Dukhan", nameBangla: "সূরা আদ-দুখান", totalAyahs: 59, revelationPlace: "Makkah" },
  { id: 45, nameArabic: "سورة الجاثية", nameEnglish: "Al-Jathiya", nameBangla: "সূরা আল-জাসিয়াহ", totalAyahs: 37, revelationPlace: "Makkah" },
  { id: 46, nameArabic: "سورة الأحقاف", nameEnglish: "Al-Ahqaf", nameBangla: "সূরা আল-আহক্বাফ", totalAyahs: 35, revelationPlace: "Makkah" },
  { id: 47, nameArabic: "سورة محمد", nameEnglish: "Muhammad", nameBangla: "সূরা মুহাম্মদ", totalAyahs: 38, revelationPlace: "Madinah" },
  { id: 48, nameArabic: "سورة الفتح", nameEnglish: "Al-Fath", nameBangla: "সূরা আল-ফাতহ", totalAyahs: 29, revelationPlace: "Madinah" },
  { id: 49, nameArabic: "سورة الحجرات", nameEnglish: "Al-Hujurat", nameBangla: "সূরা আল-হুজুরাত", totalAyahs: 18, revelationPlace: "Madinah" },
  { id: 50, nameArabic: "سورة ق", nameEnglish: "Qaf", nameBangla: "সূরা ক্বাফ", totalAyahs: 45, revelationPlace: "Makkah" },

  { id: 51, nameArabic: "سورة الذاريات", nameEnglish: "Adh-Dhariyat", nameBangla: "সূরা আদ-ধারিয়াত", totalAyahs: 60, revelationPlace: "Makkah" },
  { id: 52, nameArabic: "سورة الطور", nameEnglish: "At-Tur", nameBangla: "সূরা আত-তূর", totalAyahs: 49, revelationPlace: "Makkah" },
  { id: 53, nameArabic: "سورة النجم", nameEnglish: "An-Najm", nameBangla: "সূরা আন-নাজম", totalAyahs: 62, revelationPlace: "Makkah" },
  { id: 54, nameArabic: "سورة القمر", nameEnglish: "Al-Qamar", nameBangla: "সূরা আল-ক্বামার", totalAyahs: 55, revelationPlace: "Makkah" },
  { id: 55, nameArabic: "سورة الرحمن", nameEnglish: "Ar-Rahman", nameBangla: "সূরা আর-রাহমান", totalAyahs: 78, revelationPlace: "Madinah" },
  { id: 56, nameArabic: "سورة الواقعة", nameEnglish: "Al-Waqia", nameBangla: "সূরা আল-ওয়াক্বি’আহ", totalAyahs: 96, revelationPlace: "Makkah" },
  { id: 57, nameArabic: "سورة الحديد", nameEnglish: "Al-Hadid", nameBangla: "সূরা আল-হাদীদ", totalAyahs: 29, revelationPlace: "Madinah" },
  { id: 58, nameArabic: "سورة المجادلة", nameEnglish: "Al-Mujadila", nameBangla: "সূরা আল-মুজাদালাহ", totalAyahs: 22, revelationPlace: "Madinah" },
  { id: 59, nameArabic: "سورة الحشر", nameEnglish: "Al-Hashr", nameBangla: "সূরা আল-হাশর", totalAyahs: 24, revelationPlace: "Madinah" },
  { id: 60, nameArabic: "سورة الممتحنة", nameEnglish: "Al-Mumtahina", nameBangla: "সূরা আল-মুমতাহিনা", totalAyahs: 13, revelationPlace: "Madinah" },

  { id: 61, nameArabic: "سورة الصف", nameEnglish: "As-Saff", nameBangla: "সূরা আস-সাফ", totalAyahs: 14, revelationPlace: "Madinah" },
  { id: 62, nameArabic: "سورة الجمعة", nameEnglish: "Al-Jumuah", nameBangla: "সূরা আল-জুমু’আহ", totalAyahs: 11, revelationPlace: "Madinah" },
  { id: 63, nameArabic: "سورة المنافقون", nameEnglish: "Al-Munafiqun", nameBangla: "সূরা আল-মুনাফিকূন", totalAyahs: 11, revelationPlace: "Madinah" },
  { id: 64, nameArabic: "سورة التغابن", nameEnglish: "At-Taghabun", nameBangla: "সূরা আত-তাগাবুন", totalAyahs: 18, revelationPlace: "Madinah" },
  { id: 65, nameArabic: "سورة الطلاق", nameEnglish: "At-Talaq", nameBangla: "সূরা আত-ত্বালাক্ব", totalAyahs: 12, revelationPlace: "Madinah" },
  { id: 66, nameArabic: "سورة التحريم", nameEnglish: "At-Tahrim", nameBangla: "সূরা আত-তাহরীম", totalAyahs: 12, revelationPlace: "Madinah" },
  { id: 67, nameArabic: "سورة الملك", nameEnglish: "Al-Mulk", nameBangla: "সূরা আল-মুলক", totalAyahs: 30, revelationPlace: "Makkah" },
  { id: 68, nameArabic: "سورة القلم", nameEnglish: "Al-Qalam", nameBangla: "সূরা আল-কলম", totalAyahs: 52, revelationPlace: "Makkah" },
  { id: 69, nameArabic: "سورة الحاقة", nameEnglish: "Al-Haqqah", nameBangla: "সূরা আল-হাক্কাহ", totalAyahs: 52, revelationPlace: "Makkah" },
  { id: 70, nameArabic: "سورة المعارج", nameEnglish: "Al-Ma'arij", nameBangla: "সূরা আল-মা’আরিজ", totalAyahs: 44, revelationPlace: "Makkah" },

  { id: 71, nameArabic: "سورة نوح", nameEnglish: "Nuh", nameBangla: "সূরা নূহ", totalAyahs: 28, revelationPlace: "Makkah" },
  { id: 72, nameArabic: "سورة الجن", nameEnglish: "Al-Jinn", nameBangla: "সূরা আল-জিন", totalAyahs: 28, revelationPlace: "Makkah" },
  { id: 73, nameArabic: "سورة المزمل", nameEnglish: "Al-Muzzammil", nameBangla: "সূরা আল-মুযযাম্মিল", totalAyahs: 20, revelationPlace: "Makkah" },
  { id: 74, nameArabic: "سورة المدثر", nameEnglish: "Al-Muddathir", nameBangla: "সূরা আল-মুদ্দাযির", totalAyahs: 56, revelationPlace: "Makkah" },
  { id: 75, nameArabic: "سورة القيامة", nameEnglish: "Al-Qiyamah", nameBangla: "সূরা আল-ক্বিয়ামাহ", totalAyahs: 40, revelationPlace: "Makkah" },
  { id: 76, nameArabic: "سورة الإنسان", nameEnglish: "Al-Insan", nameBangla: "সূরা আল-ইনসান", totalAyahs: 31, revelationPlace: "Madinah" },
  { id: 77, nameArabic: "سورة المرسلات", nameEnglish: "Al-Mursalat", nameBangla: "সূরা আল-মুরসালাত", totalAyahs: 50, revelationPlace: "Makkah" },
  { id: 78, nameArabic: "سورة النبأ", nameEnglish: "An-Naba", nameBangla: "সূরা আন-নাবা", totalAyahs: 40, revelationPlace: "Makkah" },
  { id: 79, nameArabic: "سورة النازعات", nameEnglish: "An-Nazi'at", nameBangla: "সূরা আন-নাজি’আত", totalAyahs: 46, revelationPlace: "Makkah" },
  { id: 80, nameArabic: "سورة عبس", nameEnglish: "Abasa", nameBangla: "সূরা আবাসা", totalAyahs: 42, revelationPlace: "Makkah" },

  { id: 81, nameArabic: "سورة التكوير", nameEnglish: "At-Takwir", nameBangla: "সূরা আত-তাক্বউইর", totalAyahs: 29, revelationPlace: "Makkah" },
  { id: 82, nameArabic: "سورة الإنفطار", nameEnglish: "Al-Infitar", nameBangla: "সূরা আল-ইনফিতার", totalAyahs: 19, revelationPlace: "Makkah" },
  { id: 83, nameArabic: "سورة المطففين", nameEnglish: "Al-Mutaffifin", nameBangla: "সূরা আল-মুতাফফিফীন", totalAyahs: 36, revelationPlace: "Makkah" },
  { id: 84, nameArabic: "سورة الإنشقاق", nameEnglish: "Al-Inshiqaq", nameBangla: "সূরা আল-ইনশিক্বাক", totalAyahs: 25, revelationPlace: "Makkah" },
  { id: 85, nameArabic: "سورة البروج", nameEnglish: "Al-Buruj", nameBangla: "সূরা আল-বুরুজ", totalAyahs: 22, revelationPlace: "Makkah" },
  { id: 86, nameArabic: "سورة الطارق", nameEnglish: "At-Tariq", nameBangla: "সূরা আত-তারিক", totalAyahs: 17, revelationPlace: "Makkah" },
  { id: 87, nameArabic: "سورة الأعلى", nameEnglish: "Al-A'la", nameBangla: "সূরা আল-আ’লা", totalAyahs: 19, revelationPlace: "Makkah" },
  { id: 88, nameArabic: "سورة الغاشية", nameEnglish: "Al-Ghashiyah", nameBangla: "সূরা আল-ঘাশিয়াহ", totalAyahs: 26, revelationPlace: "Makkah" },
  { id: 89, nameArabic: "سورة الفجر", nameEnglish: "Al-Fajr", nameBangla: "সূরা আল-ফজর", totalAyahs: 30, revelationPlace: "Makkah" },
  { id: 90, nameArabic: "سورة البلد", nameEnglish: "Al-Balad", nameBangla: "সূরা আল-বালাদ", totalAyahs: 20, revelationPlace: "Makkah" },

  { id: 91, nameArabic: "سورة الشمس", nameEnglish: "Ash-Shams", nameBangla: "সূরা আশ-শামস", totalAyahs: 15, revelationPlace: "Makkah" },
  { id: 92, nameArabic: "سورة الليل", nameEnglish: "Al-Lail", nameBangla: "সূরা আল-লাইল", totalAyahs: 21, revelationPlace: "Makkah" },
  { id: 93, nameArabic: "سورة الضحى", nameEnglish: "Ad-Duhaa", nameBangla: "সূরা আয-জুহা", totalAyahs: 11, revelationPlace: "Makkah" },
  { id: 94, nameArabic: "سورة الشرح", nameEnglish: "Ash-Sharh", nameBangla: "সূরা আশ-শরহ", totalAyahs: 8, revelationPlace: "Makkah" },
  { id: 95, nameArabic: "سورة التين", nameEnglish: "At-Tin", nameBangla: "সূরা আত-তিন", totalAyahs: 8, revelationPlace: "Makkah" },
  { id: 96, nameArabic: "سورة العلق", nameEnglish: "Al-Alaq", nameBangla: "সূরা আল-আলাক", totalAyahs: 19, revelationPlace: "Makkah" },
  { id: 97, nameArabic: "سورة القدر", nameEnglish: "Al-Qadr", nameBangla: "সূরা আল-ক্বদর", totalAyahs: 5, revelationPlace: "Makkah" },
  { id: 98, nameArabic: "سورة البينة", nameEnglish: "Al-Bayyinah", nameBangla: "সূরা আল-বায়্যিনাহ", totalAyahs: 8, revelationPlace: "Madinah" },
  { id: 99, nameArabic: "سورة الزلزلة", nameEnglish: "Az-Zalzalah", nameBangla: "সূরা আজ-জালজালাহ", totalAyahs: 8, revelationPlace: "Madinah" },
  { id: 100, nameArabic: "سورة العاديات", nameEnglish: "Al-Adiyat", nameBangla: "সূরা আল-আদিয়াত", totalAyahs: 11, revelationPlace: "Makkah" },

  { id: 101, nameArabic: "سورة القارعة", nameEnglish: "Al-Qari’ah", nameBangla: "সূরা আল-ক্বারিয়’আহ", totalAyahs: 11, revelationPlace: "Makkah" },
  { id: 102, nameArabic: "سورة التكاثر", nameEnglish: "At-Takathur", nameBangla: "সূরা আত-তাক্বাসুর", totalAyahs: 8, revelationPlace: "Makkah" },
  { id: 103, nameArabic: "سورة العصر", nameEnglish: "Al-Asr", nameBangla: "সূরা আল-আসর", totalAyahs: 3, revelationPlace: "Makkah" },
  { id: 104, nameArabic: "سورة الهمزة", nameEnglish: "Al-Humazah", nameBangla: "সূরা আল-হুমাযাহ", totalAyahs: 9, revelationPlace: "Makkah" },
  { id: 105, nameArabic: "سورة الفيل", nameEnglish: "Al-Fil", nameBangla: "সূরা আল-ফীল", totalAyahs: 5, revelationPlace: "Makkah" },
  { id: 106, nameArabic: "سورة قريش", nameEnglish: "Quraish", nameBangla: "সূরা কুরাইশ", totalAyahs: 4, revelationPlace: "Makkah" },
  { id: 107, nameArabic: "سورة الماعون", nameEnglish: "Al-Ma’un", nameBangla: "সূরা আল-মাউন", totalAyahs: 7, revelationPlace: "Makkah" },
  { id: 108, nameArabic: "سورة الكوثر", nameEnglish: "Al-Kawthar", nameBangla: "সূরা আল-কাউসার", totalAyahs: 3, revelationPlace: "Makkah" },
  { id: 109, nameArabic: "سورة الكافرون", nameEnglish: "Al-Kafirun", nameBangla: "সূরা আল-কাফিরূন", totalAyahs: 6, revelationPlace: "Makkah" },
  { id: 110, nameArabic: "سورة النصر", nameEnglish: "An-Nasr", nameBangla: "সূরা আন-নস্র", totalAyahs: 3, revelationPlace: "Madinah" },

  { id: 111, nameArabic: "سورة المسد", nameEnglish: "Al-Masad", nameBangla: "সূরা আল-মাসাদ", totalAyahs: 5, revelationPlace: "Makkah" },
  { id: 112, nameArabic: "سورة الإخلاص", nameEnglish: "Al-Ikhlas", nameBangla: "সূরা আল-ইখলাস", totalAyahs: 4, revelationPlace: "Makkah" },
  { id: 113, nameArabic: "سورة الفلق", nameEnglish: "Al-Falaq", nameBangla: "সূরা আল-ফালাক", totalAyahs: 5, revelationPlace: "Makkah" },
  { id: 114, nameArabic: "سورة الناس", nameEnglish: "An-Nas", nameBangla: "সূরা আন-নাস", totalAyahs: 6, revelationPlace: "Makkah" }
];
