// suras.js
// সব সূরার তালিকা — ১ থেকে ১১৪
// প্রত্যেকটার file: "surah_XXX.json" (তুমি যেইভাবে এখন রাখছো সেই ফরম্যাট)

const suras = [
  { number: 1,  nameAr: "سورة الفاتحة",        nameBn: "সূরা আল-ফাতিহা",          type: "Makki",  ayahCount: 7,  file: "surah_001.json" },
  { number: 2,  nameAr: "سورة البقرة",         nameBn: "সূরা আল-বাকারা",          type: "Madani", ayahCount: 286,file: "surah_002.json" },
  { number: 3,  nameAr: "سورة آل عمران",       nameBn: "সূরা আলে-ইমরান",          type: "Madani", ayahCount: 200,file: "surah_003.json" },
  { number: 4,  nameAr: "سورة النساء",         nameBn: "সূরা আন-নিসা",            type: "Madani", ayahCount: 176,file: "surah_004.json" },
  { number: 5,  nameAr: "سورة المائدة",        nameBn: "সূরা আল-মায়িদাহ",         type: "Madani", ayahCount: 120,file: "surah_005.json" },
  { number: 6,  nameAr: "سورة الأنعام",        nameBn: "সূরা আল-আনআাম",           type: "Makki",  ayahCount: 165,file: "surah_006.json" },
  { number: 7,  nameAr: "سورة الأعراف",        nameBn: "সূরা আল-আ’রাফ",           type: "Makki",  ayahCount: 206,file: "surah_007.json" },
  { number: 8,  nameAr: "سورة الأنفال",        nameBn: "সূরা আল-আনফাল",           type: "Madani", ayahCount: 75, file: "surah_008.json" },
  { number: 9,  nameAr: "سورة التوبة",         nameBn: "সূরা আত-তাওবা",           type: "Madani", ayahCount: 129,file: "surah_009.json" },
  { number: 10, nameAr: "سورة يونس",           nameBn: "সূরা ইউনুস",              type: "Makki",  ayahCount: 109,file: "surah_010.json" },
  { number: 11, nameAr: "سورة هود",            nameBn: "সূরা হুদ",                type: "Makki",  ayahCount: 123,file: "surah_011.json" },
  { number: 12, nameAr: "سورة يوسف",          nameBn: "সূরা ইউসুফ",              type: "Makki",  ayahCount: 111,file: "surah_012.json" },
  { number: 13, nameAr: "سورة الرعد",          nameBn: "সূরা আর-রা'দ",            type: "Madani", ayahCount: 43, file: "surah_013.json" },
  { number: 14, nameAr: "سورة إبراهيم",        nameBn: "সূরা ইবরাহীম",            type: "Makki",  ayahCount: 52, file: "surah_014.json" },
  { number: 15, nameAr: "سورة الحجر",          nameBn: "সূরা আল-হিজর",            type: "Makki",  ayahCount: 99, file: "surah_015.json" },
  { number: 16, nameAr: "سورة النحل",          nameBn: "সূরা আন-নাহল",            type: "Makki",  ayahCount: 128,file: "surah_016.json" },
  { number: 17, nameAr: "سورة الإسراء",        nameBn: "সূরা আল-ইসরা (বনি ইসরাইল)",type: "Makki", ayahCount: 111,file: "surah_017.json" },
  { number: 18, nameAr: "سورة الكهف",          nameBn: "সূরা আল-কাহফ",            type: "Makki",  ayahCount: 110,file: "surah_018.json" },
  { number: 19, nameAr: "سورة مريم",           nameBn: "সূরা মরিয়ম",             type: "Makki",  ayahCount: 98, file: "surah_019.json" },
  { number: 20, nameAr: "سورة طه",             nameBn: "সূরা ত্বা-হা",             type: "Makki",  ayahCount: 135,file: "surah_020.json" },
  { number: 21, nameAr: "سورة الأنبياء",       nameBn: "সূরা আল-আম্বিয়া",        type: "Makki",  ayahCount: 112,file: "surah_021.json" },
  { number: 22, nameAr: "سورة الحج",           nameBn: "সূরা আল-হাজ্জ",           type: "Madani", ayahCount: 78, file: "surah_022.json" },
  { number: 23, nameAr: "سورة المؤمنون",       nameBn: "সূরা আল-মু'মিনুন",        type: "Makki",  ayahCount: 118,file: "surah_023.json" },
  { number: 24, nameAr: "سورة النور",          nameBn: "সূরা আন-নূর",             type: "Madani", ayahCount: 64, file: "surah_024.json" },
  { number: 25, nameAr: "سورة الفرقان",        nameBn: "সূরা আল-ফুরকান",          type: "Makki",  ayahCount: 77, file: "surah_025.json" },
  { number: 26, nameAr: "سورة الشعراء",        nameBn: "সূরা আশ-শু'আরা",         type: "Makki",  ayahCount: 227,file: "surah_026.json" },
  { number: 27, nameAr: "سورة النمل",          nameBn: "সূরা আন-নামল",            type: "Makki",  ayahCount: 93, file: "surah_027.json" },
  { number: 28, nameAr: "سورة القصص",          nameBn: "সূরা আল-কাসাস",           type: "Makki",  ayahCount: 88, file: "surah_028.json" },
  { number: 29, nameAr: "سورة العنكبوت",       nameBn: "সূরা আল-আনকাবূত",         type: "Makki",  ayahCount: 69, file: "surah_029.json" },
  { number: 30, nameAr: "سورة الروم",          nameBn: "সূরা আর-রূম",             type: "Makki",  ayahCount: 60, file: "surah_030.json" },
  { number: 31, nameAr: "سورة لقمان",          nameBn: "সূরা লুকমান",             type: "Makki",  ayahCount: 34, file: "surah_031.json" },
  { number: 32, nameAr: "سورة السجدة",         nameBn: "সূরা আস-সাজদাহ",          type: "Makki",  ayahCount: 30, file: "surah_032.json" },
  { number: 33, nameAr: "سورة الأحزاب",        nameBn: "সূরা আল-আহযাব",           type: "Madani", ayahCount: 73, file: "surah_033.json" },
  { number: 34, nameAr: "سورة سبأ",            nameBn: "সূরা সাবা",               type: "Makki",  ayahCount: 54, file: "surah_034.json" },
  { number: 35, nameAr: "سورة فاطر",           nameBn: "সূরা ফাতির",              type: "Makki",  ayahCount: 45, file: "surah_035.json" },
  { number: 36, nameAr: "سورة يس",             nameBn: "সূরা ইয়াসীন",            type: "Makki",  ayahCount: 83, file: "surah_036.json" },
  { number: 37, nameAr: "سورة الصافات",        nameBn: "সূরা আস-সাফফাত",         type: "Makki",  ayahCount: 182,file: "surah_037.json" },
  { number: 38, nameAr: "سورة ص",              nameBn: "সূরা সাদ",                type: "Makki",  ayahCount: 88, file: "surah_038.json" },
  { number: 39, nameAr: "سورة الزمر",          nameBn: "সূরা আজ-জুমার",           type: "Makki",  ayahCount: 75, file: "surah_039.json" },
  { number: 40, nameAr: "سورة غافر",           nameBn: "সূরা গাফির (মু'মিন)",     type: "Makki",  ayahCount: 85, file: "surah_040.json" },
  { number: 41, nameAr: "سورة فصلت",          nameBn: "সূরা ফুসসিলাত",           type: "Makki",  ayahCount: 54, file: "surah_041.json" },
  { number: 42, nameAr: "سورة الشورى",        nameBn: "সূরা আশ-শুরা",            type: "Makki",  ayahCount: 53, file: "surah_042.json" },
  { number: 43, nameAr: "سورة الزخرف",        nameBn: "সূরা আয-যুখরুফ",          type: "Makki",  ayahCount: 89, file: "surah_043.json" },
  { number: 44, nameAr: "سورة الدخان",        nameBn: "সূরা আদ-দুখান",           type: "Makki",  ayahCount: 59, file: "surah_044.json" },
  { number: 45, nameAr: "سورة الجاثية",       nameBn: "সূরা আল-জাসিয়াহ",        type: "Makki",  ayahCount: 37, file: "surah_045.json" },
  { number: 46, nameAr: "سورة الأحقاف",       nameBn: "সূরা আল-আহকাফ",           type: "Makki",  ayahCount: 35, file: "surah_046.json" },
  { number: 47, nameAr: "سورة محمد",          nameBn: "সূরা মুহাম্মদ",           type: "Madani", ayahCount: 38, file: "surah_047.json" },
  { number: 48, nameAr: "سورة الفتح",         nameBn: "সূরা আল-ফাতহ",            type: "Madani", ayahCount: 29, file: "surah_048.json" },
  { number: 49, nameAr: "سورة الحجرات",       nameBn: "সূরা আল-হুজুরাত",         type: "Madani", ayahCount: 18, file: "surah_049.json" },
  { number: 50, nameAr: "سورة ق",             nameBn: "সূরা কাফ",                type: "Makki",  ayahCount: 45, file: "surah_050.json" },
  { number: 51, nameAr: "سورة الذاريات",      nameBn: "সূরা আয-যারিয়াত",        type: "Makki",  ayahCount: 60, file: "surah_051.json" },
  { number: 52, nameAr: "سورة الطور",         nameBn: "সূরা আত-তুর",             type: "Makki",  ayahCount: 49, file: "surah_052.json" },
  { number: 53, nameAr: "سورة النجم",         nameBn: "সূরা আন-নাজম",            type: "Makki",  ayahCount: 62, file: "surah_053.json" },
  { number: 54, nameAr: "سورة القمر",         nameBn: "সূরা আল-কামার",           type: "Makki",  ayahCount: 55, file: "surah_054.json" },
  { number: 55, nameAr: "سورة الرحمن",        nameBn: "সূরা আর-রহমান",           type: "Madani", ayahCount: 78, file: "surah_055.json" },
  { number: 56, nameAr: "سورة الواقعة",       nameBn: "সূরা আল-ওয়াকিয়া",       type: "Makki",  ayahCount: 96, file: "surah_056.json" },
  { number: 57, nameAr: "سورة الحديد",        nameBn: "সূরা আল-হাদীদ",           type: "Madani", ayahCount: 29, file: "surah_057.json" },
  { number: 58, nameAr: "سورة المجادلة",      nameBn: "সূরা আল-মুজাদালাহ",      type: "Madani", ayahCount: 22, file: "surah_058.json" },
  { number: 59, nameAr: "سورة الحشر",         nameBn: "সূরা আল-হাশর",            type: "Madani", ayahCount: 24, file: "surah_059.json" },
  { number: 60, nameAr: "سورة الممتحنة",      nameBn: "সূরা আল-মুমতাহিনা",      type: "Madani", ayahCount: 13, file: "surah_060.json" },
  { number: 61, nameAr: "سورة الصف",          nameBn: "সূরা আস-সাফ",             type: "Madani", ayahCount: 14, file: "surah_061.json" },
  { number: 62, nameAr: "سورة الجمعة",        nameBn: "সূরা আল-জুমু'আহ",         type: "Madani", ayahCount: 11, file: "surah_062.json" },
  { number: 63, nameAr: "سورة المنافقون",     nameBn: "সূরা আল-মুনাফিকুন",      type: "Madani", ayahCount: 11, file: "surah_063.json" },
  { number: 64, nameAr: "سورة التغابن",       nameBn: "সূরা আত-তাগাবুন",        type: "Madani", ayahCount: 18, file: "surah_064.json" },
  { number: 65, nameAr: "سورة الطلاق",        nameBn: "সূরা আত-তালাক",           type: "Madani", ayahCount: 12, file: "surah_065.json" },
  { number: 66, nameAr: "سورة التحريم",       nameBn: "সূরা আত-তাহরীম",         type: "Madani", ayahCount: 12, file: "surah_066.json" },
  { number: 67, nameAr: "سورة الملك",         nameBn: "সূরা আল-মুলক",           type: "Makki",  ayahCount: 30, file: "surah_067.json" },
  { number: 68, nameAr: "سورة القلم",         nameBn: "সূরা আল-কলম",            type: "Makki",  ayahCount: 52, file: "surah_068.json" },
  { number: 69, nameAr: "سورة الحاقة",        nameBn: "সূরা আল-হাক্বকাহ",        type: "Makki",  ayahCount: 52, file: "surah_069.json" },
  { number: 70, nameAr: "سورة المعارج",       nameBn: "সূরা আল-মা'আরিজ",        type: "Makki",  ayahCount: 44, file: "surah_070.json" },
  { number: 71, nameAr: "سورة نوح",           nameBn: "সূরা নূহ",                type: "Makki",  ayahCount: 28, file: "surah_071.json" },
  { number: 72, nameAr: "سورة الجن",          nameBn: "সূরা আল-জিন",             type: "Makki",  ayahCount: 28, file: "surah_072.json" },
  { number: 73, nameAr: "سورة المزمل",        nameBn: "সূরা আল-মুজ্জাম্মিল",    type: "Makki",  ayahCount: 20, file: "surah_073.json" },
  { number: 74, nameAr: "سورة المدثر",        nameBn: "সূরা আল-মুদ্দাস্সির",    type: "Makki",  ayahCount: 56, file: "surah_074.json" },
  { number: 75, nameAr: "سورة القيامة",       nameBn: "সূরা আল-কেয়ামাহ",       type: "Makki",  ayahCount: 40, file: "surah_075.json" },
  { number: 76, nameAr: "سورة الإنسان",       nameBn: "সূরা আল-ইনসান (আদ-দাহর)", type: "Madani",ayahCount: 31, file: "surah_076.json" },
  { number: 77, nameAr: "سورة المرسلات",      nameBn: "সূরা আল-মুরসালাত",       type: "Makki",  ayahCount: 50, file: "surah_077.json" },
  { number: 78, nameAr: "سورة النبأ",         nameBn: "সূরা আন-নাবা",            type: "Makki",  ayahCount: 40, file: "surah_078.json" },
  { number: 79, nameAr: "سورة النازعات",      nameBn: "সূরা আন-নাযিয়াত",        type: "Makki",  ayahCount: 46, file: "surah_079.json" },
  { number: 80, nameAr: "سورة عبس",           nameBn: "সূরা আবাসা",              type: "Makki",  ayahCount: 42, file: "surah_080.json" },
  { number: 81, nameAr: "سورة التكوير",       nameBn: "সূরা আত-তাকবীর",         type: "Makki",  ayahCount: 29, file: "surah_081.json" },
  { number: 82, nameAr: "سورة الانفطار",      nameBn: "সূরা আল-ইনফিতার",        type: "Makki",  ayahCount: 19, file: "surah_082.json" },
  { number: 83, nameAr: "سورة المطففين",      nameBn: "সূরা আল-মুতাফফিফিন",    type: "Makki",  ayahCount: 36, file: "surah_083.json" },
  { number: 84, nameAr: "سورة الانشقاق",      nameBn: "সূরা আল-ইনশিক্বাক",      type: "Makki",  ayahCount: 25, file: "surah_084.json" },
  { number: 85, nameAr: "سورة البروج",        nameBn: "সূরা আল-বুরুজ",          type: "Makki",  ayahCount: 22, file: "surah_085.json" },
  { number: 86, nameAr: "سورة الطارق",        nameBn: "সূরা আত-তারিক",          type: "Makki",  ayahCount: 17, file: "surah_086.json" },
  { number: 87, nameAr: "سورة الأعلى",        nameBn: "সূরা আল-আ'লা",           type: "Makki",  ayahCount: 19, file: "surah_087.json" },
  { number: 88, nameAr: "سورة الغاشية",       nameBn: "সূরা আল-গাশিয়াহ",       type: "Makki",  ayahCount: 26, file: "surah_088.json" },
  { number: 89, nameAr: "سورة الفجر",         nameBn: "সূরা আল-ফাজর",           type: "Makki",  ayahCount: 30, file: "surah_089.json" },
  { number: 90, nameAr: "سورة البلد",         nameBn: "সূরা আল-বালাদ",          type: "Makki",  ayahCount: 20, file: "surah_090.json" },
  { number: 91, nameAr: "سورة الشمس",         nameBn: "সূরা আশ-শামস",          type: "Makki",  ayahCount: 15, file: "surah_091.json" },
  { number: 92, nameAr: "سورة الليل",         nameBn: "সূরা আল-লাইল",           type: "Makki",  ayahCount: 21, file: "surah_092.json" },
  { number: 93, nameAr: "سورة الضحى",         nameBn: "সূরা আদ-দুহা",           type: "Makki",  ayahCount: 11, file: "surah_093.json" },
  { number: 94, nameAr: "سورة الشرح",         nameBn: "সূরা আশ-শারহ (আল-ইনশিরাহ)",type:"Makki",ayahCount: 8, file: "surah_094.json" },
  { number: 95, nameAr: "سورة التين",         nameBn: "সূরা আত-তীন",            type: "Makki",  ayahCount: 8, file: "surah_095.json" },
  { number: 96, nameAr: "سورة العلق",         nameBn: "সূরা আল-আলাক",           type: "Makki",  ayahCount: 19, file: "surah_096.json" },
  { number: 97, nameAr: "سورة القدر",         nameBn: "সূরা আল-কদর",            type: "Makki",  ayahCount: 5,  file: "surah_097.json" },
  { number: 98, nameAr: "سورة البينة",        nameBn: "সূরা আল-বাইয়্যিনাহ",     type: "Madani", ayahCount: 8,  file: "surah_098.json" },
  { number: 99, nameAr: "سورة الزلزلة",       nameBn: "সূরা আয-যালযালাহ",       type: "Madani", ayahCount: 8,  file: "surah_099.json" },
  { number: 100,nameAr: "سورة العاديات",      nameBn: "সূরা আল-আদিয়াত",         type: "Makki",  ayahCount: 11, file: "surah_100.json" },
  { number: 101,nameAr: "سورة القارعة",       nameBn: "সূরা আল-কারি'আহ",        type: "Makki",  ayahCount: 11, file: "surah_101.json" },
  { number: 102,nameAr: "سورة التكاثر",       nameBn: "সূরা আত-তাকাসুর",        type: "Makki",  ayahCount: 8,  file: "surah_102.json" },
  { number: 103,nameAr: "سورة العصر",         nameBn: "সূরা আল-'আসর",           type: "Makki",  ayahCount: 3,  file: "surah_103.json" },
  { number: 104,nameAr: "سورة الهمزة",        nameBn: "সূরা আল-হুমাযাহ",        type: "Makki",  ayahCount: 9,  file: "surah_104.json" },
  { number: 105,nameAr: "سورة الفيل",         nameBn: "সূরা আল-ফীল",            type: "Makki",  ayahCount: 5,  file: "surah_105.json" },
  { number: 106,nameAr: "سورة قريش",          nameBn: "সূরা কুরাইশ",            type: "Makki",  ayahCount: 4,  file: "surah_106.json" },
  { number: 107,nameAr: "سورة الماعون",       nameBn: "সূরা আল-মাউন",           type: "Makki",  ayahCount: 7,  file: "surah_107.json" },
  { number: 108,nameAr: "سورة الكوثر",        nameBn: "সূরা আল-কাওসার",         type: "Makki",  ayahCount: 3,  file: "surah_108.json" },
  { number: 109,nameAr: "سورة الكافرون",      nameBn: "সূরা আল-কাফিরুন",        type: "Makki",  ayahCount: 6,  file: "surah_109.json" },
  { number: 110,nameAr: "سورة النصر",         nameBn: "সূরা আন-নাসর",           type: "Madani", ayahCount: 3,  file: "surah_110.json" },
  { number: 111,nameAr: "سورة المسد",         nameBn: "সূরা আল-মাসাদ",          type: "Makki",  ayahCount: 5,  file: "surah_111.json" },
  { number: 112,nameAr: "سورة الإخلاص",       nameBn: "সূরা আল-ইখলাস",          type: "Makki",  ayahCount: 4,  file: "surah_112.json" },
  { number: 113,nameAr: "سورة الفلق",         nameBn: "সূরা আল-ফালাক",          type: "Makki",  ayahCount: 5,  file: "surah_113.json" },
  { number: 114,nameAr: "سورة الناس",         nameBn: "সূরা আন-নাস",            type: "Makki",  ayahCount: 6,  file: "surah_114.json" }
];

// চাইলে debug এর জন্য:
// console.log("Total suras:", suras.length);
